#!/bin/sh

CURDIR=`pwd`
UPSTREAMVERSION=`head -n1 changelog.debian | cut -d"(" -f2 | cut -d"-" -f1`
DESTDIR=/tmp/qmagneto-$UPSTREAMVERSION
rm $DESTDIR -rf
mkdir $DESTDIR
cp debian info.txt qmagneto.pro resources src ui $DESTDIR -R 

cp changelog.debian $DESTDIR/debian/changelog
echo "3.0 (quilt)" > $DESTDIR/debian/source/format
cd $DESTDIR
rm $DESTDIR/../qmagneto_*
find $DESTDIR -name "*.svn" -exec rm {} -rf \; 2>/dev/null
tar cfz ../qmagneto_$UPSTREAMVERSION.orig.tar.gz ../qmagneto-$UPSTREAMVERSION --exclude .svn --exclude debian 
debuild -S -sa
ls -I $DESTDIR /tmp/qmagneto_*
cd $CURDIR
