#!/bin/sh

CURDIR=`pwd`
VERSION=`head -n1 changelog.ubuntu | cut -d"(" -f2 | cut -d"-" -f1`
DESTDIR=/tmp/qmagneto-$VERSION
rm $DESTDIR -rf
mkdir $DESTDIR
cp debian info.txt qmagneto.pro resources src ui $DESTDIR -R 

cp changelog.ubuntu $DESTDIR/debian/changelog
echo "3.0 (native)" > $DESTDIR/debian/source/format
cd $DESTDIR
rm $DESTDIR/../qmagneto_*
find $DESTDIR -name "*.svn" -exec rm {} -rf \; 2>/dev/null
debuild --no-tgz-check -S -sa 
ls -I $DESTDIR /tmp/qmagneto_*
cd $CURDIR

