.TH "QMagneto" "1" "Dec 01, 2010" "" ""
.SH "NAME"
QMagneto \- TV Electronic Program Guide with recording function 
.SH "SYNOPSIS"
.B qmagneto
.B \-l
.I [Language]
.SH "DESCRIPTION"
This manual page documents briefly the
.B QMagneto
commands.
.PP 
\fBQMagneto\fP is an EPG (Electronic Program Guide) which displays the TV programs.
 It also able to record programs by call an external program as VLC or mencoder. It is thus possible to record programs from a french BOX (Neufbox or Freebox) or a DVB-T device. 

.SH "OPTIONS"
.TP 
.B \-l [Language]
Force QMagneto to use Language instead of the system language.
Available languages are English and French
.SH "SEE ALSO"
.BR xmltv (3),
.br 
.SH "AUTHOR"
QMagneto was written by Jean\-Luc Biord <jlbiord@gmail.com>.
.PP 
This manual page was written by Jean\-Luc Biord <jlbiord@gmail.com>.

